#!/usr/bin/env bash

freq=3600

cd "$(dirname "$0")"

while true; do

    # Kill one if more than one running
    ps aux | \
        grep -P julia-julia | \
        grep -v $$ | \
        grep -P "bash" | \
        grep -oP "^[[:alnum:]]+\s+\d+\s" | \
        grep -oP "\d+" | \
        xargs kill -9

    # Get last run time
    while read -r line; do
        last_run="$line"
    done < "./data/time.txt"

    # Get current time
    current_time=$(date +%s)

    # Get time difference
    time_diff=$((current_time-last_run))
    echo "Time since last run (s):"
    echo $time_diff

    # Run if time difference is large
    if [ $time_diff -ge $freq ]; then
        echo $current_time > data/time.txt
        bash build.sh
    fi

    # Try again soon
    sleep 60
done
